version: '3'

services:
  app1_instancia1:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: pos-facef/app1:v1.0.0
    restart: always
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      IS_RETURN_200: 1 ## NEW CODE
    networks:
      - app-network
  
  app1_instancia2:
    build:
      context: .
      dockerfile: app1/Dockerfile
    image: pos-facef/app1:v1.0.0
    restart: always
    ports:
      - "3002:3000"
    environment:
      PORT: 3000
      IS_RETURN_200: 0 ## NEW CODE
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app1/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - app1_instancia1
      - app1_instancia2
    networks:
      - app-network
  
  ## START NEW CODE
  app2_instancia1:
    build:
      context: .
      dockerfile: app2/Dockerfile
    image: pos-facef/app2:v1.0.0
    restart: always
    ports:
      - "3003:3000"
    environment:
      PORT: 3000
      NGINX_URL: "http://nginx:80"
    depends_on:
      - nginx
    networks:
      - app-network
  ## END NEW CODE

networks:
  app-network:
    driver: bridge